### ISSUE TITLE
The latest published release fails to build with Rust > 1.79

### ISSUE THREAD

**Issue by 0323pin** [aome510/hackernews-TUI#107]
Hi,

FYI, see title.
This is because the time crate fails with:
```
error[E0282]: type annotations needed for `Box<_>`
  --> /pbulk/work/devel/cargo-outdated/work/vendor/time-0.3.30/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++
```
The solution is to update time to 0.3.36 and cut a new release.

**Comment by 0323pin** [comment]
That would be awesome, thanks.

**Comment by aome510** [comment]
Just published a new release: https://github.com/aome510/hackernews-TUI/releases/tag/v0.13.5

**Comment by 0323pin** [comment]
@aome510 thank you!

**Comment by 0323pin** [comment]
[Merged](http://mail-index.netbsd.org/pkgsrc-changes/2024/10/22/msg309269.html)
